import tkinter
import random
AGN = []
def gen():
	a = Lg.get()
	b = Rg.get()
	c = random.randint(a, b)
	str(c)
	AGN.append(c)
	RPLabel.configure(text=c)
	AGNLabel.delete(1.0, 10000.0)
	AGNLabel.insert(1.0, AGN)
#def van():
#	AGNLabel.insert(1.0, AGN)
#def can():
#	AGNLabel.delete(1.0, 100.0)
Window = tkinter.Tk()
Window.title('Генератор рандомных чисел')
Lg = tkinter.IntVar()
Rg = tkinter.IntVar()
RPLabel = tkinter.Label(text='Здесь должно быть число', justify='left')
EntryL = tkinter.Entry(width='10',  textvariable=Lg, justify='center')
Llabel =tkinter.Label(text='От:')########################################
EntryR = tkinter.Entry(width='10',  textvariable=Rg, justify='center')
Rlabel = tkinter.Label(text='До:')
GButton = tkinter.Button(text='Сгенерировать', command=gen)
AGNLabel = tkinter.Text(width=44, height=39)
PZBLabel = tkinter.Label(text='Список сгенерированнных чисел')
#CANButton = tkinter.Button(text='Очистить', command=can)
#VANButton = tkinter.Button(text='Показать все числа', command=van)
scroll = tkinter.Scrollbar(command=AGNLabel.yview)
scroll.pack(side = 'right', fill = 'y' )
AGNLabel.config(yscrollcommand=scroll.set)
#VANButton.place(x='300', y='1400')
#CANButton.place(x='0', y='1400')
PZBLabel.place(x='30', y='2100')
GButton.place(x='0', y='0')
EntryR.place(x='659', y='200')
Rlabel.place(x='580', y='200')
EntryL.place(x='270', y='200')
Llabel.place(x='200', y='200')
RPLabel.place(x='430', y='0')
AGNLabel.place(x='0', y='260')
tkinter.mainloop()
